; Auto-generated. Do not edit!


(cl:in-package robot_soccer-msg)


;//! \htmlinclude MotionFeedback.msg.html

(cl:defclass <MotionFeedback> (roslisp-msg-protocol:ros-message)
  ((status_message
    :reader status_message
    :initarg :status_message
    :type cl:string
    :initform ""))
)

(cl:defclass MotionFeedback (<MotionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_soccer-msg:<MotionFeedback> is deprecated: use robot_soccer-msg:MotionFeedback instead.")))

(cl:ensure-generic-function 'status_message-val :lambda-list '(m))
(cl:defmethod status_message-val ((m <MotionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_soccer-msg:status_message-val is deprecated.  Use robot_soccer-msg:status_message instead.")
  (status_message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotionFeedback>) ostream)
  "Serializes a message object of type '<MotionFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status_message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status_message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotionFeedback>) istream)
  "Deserializes a message object of type '<MotionFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status_message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status_message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotionFeedback>)))
  "Returns string type for a message object of type '<MotionFeedback>"
  "robot_soccer/MotionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotionFeedback)))
  "Returns string type for a message object of type 'MotionFeedback"
  "robot_soccer/MotionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotionFeedback>)))
  "Returns md5sum for a message object of type '<MotionFeedback>"
  "1ee1e12fac87e0e1fb2337335c802b2b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotionFeedback)))
  "Returns md5sum for a message object of type 'MotionFeedback"
  "1ee1e12fac87e0e1fb2337335c802b2b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotionFeedback>)))
  "Returns full string definition for message of type '<MotionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string status_message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotionFeedback)))
  "Returns full string definition for message of type 'MotionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string status_message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotionFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status_message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MotionFeedback
    (cl:cons ':status_message (status_message msg))
))
