; Auto-generated. Do not edit!


(cl:in-package robot_soccer-msg)


;//! \htmlinclude MotionGoal.msg.html

(cl:defclass <MotionGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:fixnum
    :initform 0))
)

(cl:defclass MotionGoal (<MotionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_soccer-msg:<MotionGoal> is deprecated: use robot_soccer-msg:MotionGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <MotionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_soccer-msg:command-val is deprecated.  Use robot_soccer-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotionGoal>) ostream)
  "Serializes a message object of type '<MotionGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'command)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotionGoal>) istream)
  "Deserializes a message object of type '<MotionGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'command)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotionGoal>)))
  "Returns string type for a message object of type '<MotionGoal>"
  "robot_soccer/MotionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotionGoal)))
  "Returns string type for a message object of type 'MotionGoal"
  "robot_soccer/MotionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotionGoal>)))
  "Returns md5sum for a message object of type '<MotionGoal>"
  "36e1d21d1340e2a5e93f075b6457cbdf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotionGoal)))
  "Returns md5sum for a message object of type 'MotionGoal"
  "36e1d21d1340e2a5e93f075b6457cbdf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotionGoal>)))
  "Returns full string definition for message of type '<MotionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotionGoal)))
  "Returns full string definition for message of type 'MotionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotionGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MotionGoal
    (cl:cons ':command (command msg))
))
