; Auto-generated. Do not edit!


(cl:in-package robot_soccer-msg)


;//! \htmlinclude MotionResult.msg.html

(cl:defclass <MotionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MotionResult (<MotionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MotionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MotionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_soccer-msg:<MotionResult> is deprecated: use robot_soccer-msg:MotionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MotionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_soccer-msg:success-val is deprecated.  Use robot_soccer-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MotionResult>) ostream)
  "Serializes a message object of type '<MotionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MotionResult>) istream)
  "Deserializes a message object of type '<MotionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MotionResult>)))
  "Returns string type for a message object of type '<MotionResult>"
  "robot_soccer/MotionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MotionResult)))
  "Returns string type for a message object of type 'MotionResult"
  "robot_soccer/MotionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MotionResult>)))
  "Returns md5sum for a message object of type '<MotionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MotionResult)))
  "Returns md5sum for a message object of type 'MotionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MotionResult>)))
  "Returns full string definition for message of type '<MotionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MotionResult)))
  "Returns full string definition for message of type 'MotionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MotionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MotionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MotionResult
    (cl:cons ':success (success msg))
))
