// Generated by gencpp from file robot_soccer/gameState.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_GAMESTATE_H
#define ROBOT_SOCCER_MESSAGE_GAMESTATE_H

#include <ros/service_traits.h>


#include <robot_soccer/gameStateRequest.h>
#include <robot_soccer/gameStateResponse.h>


namespace robot_soccer
{

struct gameState
{

typedef gameStateRequest Request;
typedef gameStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gameState
} // namespace robot_soccer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_soccer::gameState > {
  static const char* value()
  {
    return "f362d485cfee2365e9883ed5f96ae587";
  }

  static const char* value(const ::robot_soccer::gameState&) { return value(); }
};

template<>
struct DataType< ::robot_soccer::gameState > {
  static const char* value()
  {
    return "robot_soccer/gameState";
  }

  static const char* value(const ::robot_soccer::gameState&) { return value(); }
};


// service_traits::MD5Sum< ::robot_soccer::gameStateRequest> should match
// service_traits::MD5Sum< ::robot_soccer::gameState >
template<>
struct MD5Sum< ::robot_soccer::gameStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::gameState >::value();
  }
  static const char* value(const ::robot_soccer::gameStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::gameStateRequest> should match
// service_traits::DataType< ::robot_soccer::gameState >
template<>
struct DataType< ::robot_soccer::gameStateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::gameState >::value();
  }
  static const char* value(const ::robot_soccer::gameStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_soccer::gameStateResponse> should match
// service_traits::MD5Sum< ::robot_soccer::gameState >
template<>
struct MD5Sum< ::robot_soccer::gameStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::gameState >::value();
  }
  static const char* value(const ::robot_soccer::gameStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::gameStateResponse> should match
// service_traits::DataType< ::robot_soccer::gameState >
template<>
struct DataType< ::robot_soccer::gameStateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::gameState >::value();
  }
  static const char* value(const ::robot_soccer::gameStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_GAMESTATE_H
