// Generated by gencpp from file robot_soccer/gameStateRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_GAMESTATEREQUEST_H
#define ROBOT_SOCCER_MESSAGE_GAMESTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_soccer
{
template <class ContainerAllocator>
struct gameStateRequest_
{
  typedef gameStateRequest_<ContainerAllocator> Type;

  gameStateRequest_()
    : state(0)  {
    }
  gameStateRequest_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::robot_soccer::gameStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_soccer::gameStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gameStateRequest_

typedef ::robot_soccer::gameStateRequest_<std::allocator<void> > gameStateRequest;

typedef boost::shared_ptr< ::robot_soccer::gameStateRequest > gameStateRequestPtr;
typedef boost::shared_ptr< ::robot_soccer::gameStateRequest const> gameStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_soccer::gameStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_soccer::gameStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_soccer::gameStateRequest_<ContainerAllocator1> & lhs, const ::robot_soccer::gameStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_soccer::gameStateRequest_<ContainerAllocator1> & lhs, const ::robot_soccer::gameStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_soccer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::gameStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::gameStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::gameStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "800f34bc468def1d86e2d42bea5648c0";
  }

  static const char* value(const ::robot_soccer::gameStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x800f34bc468def1dULL;
  static const uint64_t static_value2 = 0x86e2d42bea5648c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_soccer/gameStateRequest";
  }

  static const char* value(const ::robot_soccer::gameStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 state\n"
;
  }

  static const char* value(const ::robot_soccer::gameStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gameStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_soccer::gameStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_soccer::gameStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_GAMESTATEREQUEST_H
