// Generated by gencpp from file robot_soccer/MotionFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_MOTIONFEEDBACK_H
#define ROBOT_SOCCER_MESSAGE_MOTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_soccer
{
template <class ContainerAllocator>
struct MotionFeedback_
{
  typedef MotionFeedback_<ContainerAllocator> Type;

  MotionFeedback_()
    : status_message()  {
    }
  MotionFeedback_(const ContainerAllocator& _alloc)
    : status_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::robot_soccer::MotionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_soccer::MotionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MotionFeedback_

typedef ::robot_soccer::MotionFeedback_<std::allocator<void> > MotionFeedback;

typedef boost::shared_ptr< ::robot_soccer::MotionFeedback > MotionFeedbackPtr;
typedef boost::shared_ptr< ::robot_soccer::MotionFeedback const> MotionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_soccer::MotionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_soccer::MotionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_soccer::MotionFeedback_<ContainerAllocator1> & lhs, const ::robot_soccer::MotionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_soccer::MotionFeedback_<ContainerAllocator1> & lhs, const ::robot_soccer::MotionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_soccer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::MotionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::MotionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::MotionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ee1e12fac87e0e1fb2337335c802b2b";
  }

  static const char* value(const ::robot_soccer::MotionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ee1e12fac87e0e1ULL;
  static const uint64_t static_value2 = 0xfb2337335c802b2bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_soccer/MotionFeedback";
  }

  static const char* value(const ::robot_soccer::MotionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string status_message\n"
;
  }

  static const char* value(const ::robot_soccer::MotionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_soccer::MotionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_soccer::MotionFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_MOTIONFEEDBACK_H
